In [40]:
# 数据的导入
import pandas as pd

df = pd.read_csv('./data/employees.csv')
df.head()

,employee_id,first_name,last_name,email,phone_number,job_id,salary,commission_pct,manager_id,department_id
0,100,Steven,King,SKING,515.123.4567,AD_PRES,24000.0,NaN,NaN,90.0
1,101,N_ann,Kochhar,NKOCHHAR,515.123.4568,AD_VP,17000.0,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,AD_VP,17000.0,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,IT_PROG,9000.0,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,IT_PROG,6000.0,NaN,103.0,60.0

In [41]:
df.salary.mean().round(1)

np.float64(6461.7)

In [42]:
df = df.tail()
df.to_csv('./data/new.csv')

In [43]:
# json
df = pd.read_json('data/data1.json')
df

   id name  age
0   1   张三   25
1   2   李四   30
2   3   王五   28

In [44]:
import json
with open('data/test.json', 'r') as f:
    data = json.load(f)
data

{'users': [{'id': 1,
   'name': '张三',
   'age': 28,
   'email': 'zhangsan@example.com',
   'is_active': True,
   'join_date': '2022-03-15'},
  {'id': 2,
   'name': '李四',
   'age': 35,
   'email': 'lisi@example.com',
   'is_active': False,
   'join_date': '2021-11-02'},
  {'id': 3,
   'name': '王五',
   'age': 24,
   'email': 'wangwu@example.com',
   'is_active': True,
   'join_date': '2023-01-20'}]}

In [45]:
df = pd.DataFrame(data['users'])
df

   id name  age                 email  is_active   join_date
0   1   张三   28  zhangsan@example.com       True  2022-03-15
1   2   李四   35      lisi@example.com      False  2021-11-02
2   3   王五   24    wangwu@example.com       True  2023-01-20