In [1]:
import numpy as np
# 分组聚合
# df.groupby('分组的字段')['聚合的字段'].聚合函数()

import pandas as pd
df = pd.read_csv('../data/employees.csv')
df

,employee_id,first_name,last_name,email,phone_number,job_id,salary,commission_pct,manager_id,department_id
0,100,Steven,King,SKING,515.123.4567,AD_PRES,24000.0,NaN,NaN,90.0
1,101,N_ann,Kochhar,NKOCHHAR,515.123.4568,AD_VP,17000.0,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,AD_VP,17000.0,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,IT_PROG,9000.0,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,IT_PROG,6000.0,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...
102,202,Pat,Fay,PFAY,603.123.6666,MK_REP,6000.0,NaN,201.0,20.0
103,203,Susan,Mavris,SMAVRIS,515.123.7777,HR_REP,6500.0,NaN,101.0,40.0
104,204,Hermann,Baer,HBAER,515.123.8888,PR_REP,10000.0,NaN,101.0,70.0
105,205,Shelley,Higgins,SHIGGINS,515.123.8080,AC_MGR,12000.0,NaN,101.0,110.0
106,206,William,Gietz,WGIETZ,515.123.8181,AC_ACCOUNT,8300.0,NaN,205.0,110.0

In [2]:
df['department_id'] = df['department_id'].fillna(0).astype('int64')
df

,employee_id,first_name,last_name,email,phone_number,job_id,salary,commission_pct,manager_id,department_id
0,100,Steven,King,SKING,515.123.4567,AD_PRES,24000.0,NaN,NaN,90
1,101,N_ann,Kochhar,NKOCHHAR,515.123.4568,AD_VP,17000.0,NaN,100.0,90
2,102,Lex,De Haan,LDEHAAN,515.123.4569,AD_VP,17000.0,NaN,100.0,90
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,IT_PROG,9000.0,NaN,102.0,60
4,104,Bruce,Ernst,BERNST,590.423.4568,IT_PROG,6000.0,NaN,103.0,60
...,...,...,...,...,...,...,...,...,...,...
102,202,Pat,Fay,PFAY,603.123.6666,MK_REP,6000.0,NaN,201.0,20
103,203,Susan,Mavris,SMAVRIS,515.123.7777,HR_REP,6500.0,NaN,101.0,40
104,204,Hermann,Baer,HBAER,515.123.8888,PR_REP,10000.0,NaN,101.0,70
105,205,Shelley,Higgins,SHIGGINS,515.123.8080,AC_MGR,12000.0,NaN,101.0,110
106,206,William,Gietz,WGIETZ,515.123.8181,AC_ACCOUNT,8300.0,NaN,205.0,110

In [3]:
# 计算不同部门的平均薪资
df.groupby('department_id').groups

{0: [78], 10: [100], 20: [101, 102], 30: [14, 15, 16, 17, 18, 19], 40: [103], 50: [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], 60: [3, 4, 5, 6, 7], 70: [104], 80: [45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 79], 90: [0, 1, 2], 100: [8, 9, 10, 11, 12, 13], 110: [105, 106]}

In [4]:
df.groupby('department_id').get_group(20)
df2 = df.groupby('department_id')[['salary']].mean().round(0) # 先分组，后聚合
df2 = df2.reset_index()
df2.sort_values('salary', ascending=False)

    department_id   salary
9              90  19333.0
11            110  10150.0
7              70  10000.0
2              20   9500.0
8              80   8956.0
10            100   8600.0
0               0   7000.0
4              40   6500.0
6              60   5760.0
1              10   4400.0
3              30   4150.0
5              50   3476.0

In [5]:
df3 = df.groupby(['department_id', 'job_id'])[['salary']].mean().round(0)
df3

                           salary
department_id job_id
0             SA_REP       7000.0
10            AD_ASST      4400.0
20            MK_MAN      13000.0
              MK_REP       6000.0
30            PU_CLERK     2780.0
              PU_MAN      11000.0
40            HR_REP       6500.0
50            SH_CLERK     3215.0
              ST_CLERK     2785.0
              ST_MAN       7280.0
60            IT_PROG      5760.0
70            PR_REP      10000.0
80            SA_MAN      12200.0
              SA_REP       8397.0
90            AD_PRES     24000.0
              AD_VP       17000.0
100           FI_ACCOUNT   7920.0
              FI_MGR      12000.0
110           AC_ACCOUNT   8300.0
              AC_MGR      12000.0