In [1]:
# 1. 导入必要的库
import pandas as pd
import numpy as np

# 2. 导入数据
df = pd.read_csv('../data/penguins.csv')
print(df.info())
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    str
 1   island             344 non-null    str
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    str
dtypes: float64(4), str(3)
memory usage: 18.9 KB
None

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

In [2]:
# 3. 数据清洗
# 处理缺失数据
# 检查处理完毕
df2 = df
print(df2.isna().sum())
print('total rows:', df2.shape[0])
df2 = df2.dropna()
print(df2.isna().sum())
print('total rows:', df2.shape[0])

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64
total rows: 344
species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64
total rows: 333

In [3]:
# 4. 数据特征构造
# 性别转分类
df3 = df2
print(df3['sex'].dtype)
df3['sex'] = df3['sex'].astype('category')
print(df3['sex'].dtype)
# 新增 bill_ratio len / dept
df3['bill_ratio'] = (df3['bill_length_mm'] / df3['bill_depth_mm']).round(3)
df3

str
category

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,bill_ratio
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,2.091
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,2.270
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,2.239
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,1.902
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male,1.908
...,...,...,...,...,...,...,...,...
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,Female,3.445
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female,3.273
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male,3.210
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female,3.054
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male,3.099

In [4]:
# 5. 数据分析
# 体重，数据分箱，高 中 低 mass_level
df4 = df3
df4['mass_level'] = pd.cut(df4['body_mass_g'],
                           bins=[0,2000,4000,np.inf],
                           labels=['light','middle','heavy'])
# 按性别分组，按岛屿分组，agg 分别看一看 均值和数量
df4.groupby(['sex','island']).agg({
    'body_mass_g':['mean','count']
})

                  body_mass_g
                         mean count
sex    island
Female Biscoe     4319.375000    80
       Dream      3446.311475    61
       Torgersen  3395.833333    24
Male   Biscoe     5104.518072    83
       Dream      3987.096774    62
       Torgersen  4034.782609    23